name: Kong Compiler - Tests

on:
  pull_request:
    paths:
      - 'Kong/**'
  push:
    branches:
      - main
    paths:
      - 'Kong/**'

env:
  STACK_ROOT: /tmp/stack-root

jobs:
  run_kong_tests:
    defaults: 
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: run Kong unit tests
        run: make test-kong