name: Kong Compiler - Tests

on:
  pull_request:
    paths:
      - 'Kong/**'
  push:
    branches:
      - main
    paths:
      - 'Kong/**'

env:
  STACK_ROOT: /tmp/stack-root

jobs:
  run_kong_tests:
    defaults: 
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: run Kong unit tests
        run: make test-kong
      - name: run Kong functional tests
        run: |
          sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install python3-venv -y
          cd Kong/
          functionnal_tests/install_requirements.sh
          source .venv/bin/activate
          python3 functionnal_tests/run.py