name: Mirroring To Epitech
run-name: Mirroring Glados

on:
  workflow_run:
    workflows:
      - Full Project
    types:
      - completed
    branches:
      - main

jobs:
  is_mirror_repo:
    name: Check if mirror repo
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository != vars.MIRROR_URL && vars.MIRROR_URL != ''}}
    steps:
      - run: echo "Good repo - Full Project succeeded, ready to mirror"

  push_to_mirror:
    needs: [is_mirror_repo]
    name: Push to Epitech repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "git@github.com:${{ vars.MIRROR_URL }}.git"
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
